export const userData = [
  {
    name: "John Doe",
    id: "001",
    joinDate: "2020-01-15",
    role: "Software Engineer",
    status: "Active",
    experience: "4 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Michael Lee",
    id: "002",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Jane Smith",
    id: "003",
    joinDate: "2019-07-20",
    role: "Product Manager",
    status: "Inactive",
    experience: "5 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Alice Johnson",
    id: "004",
    joinDate: "2020-03-10",
    role: "Data Analyst",
    status: "Active",
    experience: "3 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Bob Williams",
    id: "005",
    joinDate: "2018-11-05",
    role: "Sales Manager",
    status: "Probation",
    experience: "6 months",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Lee Johns",
    id: "006",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Eve Brown",
    id: "007",
    joinDate: "2021-02-28",
    role: "HR Specialist",
    status: "Inactive",
    experience: "2 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Thomas Paul",
    id: "008",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "George Milton",
    id: "009",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Sam Bobby",
    id: "010",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Richard Davis",
    id: "011",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
  {
    name: "Molly Paul",
    id: "012",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "Lane1",
    department: "developer",
  },
];
